# compose.yml
services:
  chartdb-pod:
    container_name: chartdb-dev-pod
    build:
      context: .
      no_cache: true
    privileged: true
    env_file:
      - .env
    volumes:
      - ../:/app
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ~/.git-credentials:/root/.git-credentials
    working_dir: /app
    entrypoint: /usr/local/bin/entrypoint.sh
    network_mode: host
